name: ekg-cloudwatch
version: '0.0.1.3'
synopsis: An ekg backend for Amazon Cloudwatch
description: Push ekg metrics to Amazon Cloudwatch
category: Web
author: Matt Parsons
maintainer: matt@sellerlabs.com
copyright: 2016 Seller Labs
license: BSD3
github: sellerlabs/ekg-cloudwatch

dependencies:
  - base >=4.7 && <5
  - ekg-core >= 0.1 && < 1.0
  - amazonka
  - amazonka-cloudwatch
  - time
  - unordered-containers
  - text
  - lens

library:
  source-dirs: src

tests:
  ekg-cloudwatch-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ekg-cloudwatch
    - hspec
