name: ekg-cloudwatch
version: 0.0.1.5
synopsis: An ekg backend for Amazon Cloudwatch
description: Push ekg metrics to Amazon Cloudwatch
category: Web
author: Matt Parsons
maintainer: matt@sellerlabs.com
copyright: 2016 Seller Labs
license: BSD3
github: sellerlabs/ekg-cloudwatch
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >=4.7 && <5
  - ekg-core >= 0.1 && < 1.0
  - amazonka >= 1.0.0
  - amazonka-core >= 1.0.0
  - amazonka-cloudwatch >= 1.0.0
  - aeson
  - semigroups
  - bytestring
  - lens
  - resourcet
  - text
  - time
  - unordered-containers

library:
  source-dirs: src

tests:
  ekg-cloudwatch-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ekg-cloudwatch
    - hspec
